export interface PrintColumn {
  key: string;
  label: string;
}

export interface BulkPrintOptions {
  columns: PrintColumn[];
  rows: Array<Record<string, string | number | undefined | null>>;
  title?: string;
}

// Opens a print-ready window with the given records in a clean A4-friendly table
// and triggers the browser print dialog.
export function openBulkPrint({ columns, rows, title }: BulkPrintOptions): void {
  const w = window.open('', '_blank', 'width=900,height=700');
  if (!w) return;

  const head = columns.map(c => `<th>${c.label}</th>`).join('');
  const body = rows
    .map(r => `<tr>${columns.map(c => `<td>${r[c.key] ?? '-'}</td>`).join('')}</tr>`)
    .join('');

  w.document.write(`<!doctype html><html><head><title>${title || 'Bulk Print'} — Arrow Delivery</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: Arial, Helvetica, sans-serif; color: #111; padding: 24px; }
  .header { display: flex; justify-content: space-between; align-items: flex-end; border-bottom: 3px solid #111; padding-bottom: 12px; margin-bottom: 16px; }
  .header h1 { font-size: 22px; letter-spacing: 1px; }
  .header .sub { font-size: 12px; color: #555; margin-top: 4px; }
  table { width: 100%; border-collapse: collapse; font-size: 11px; }
  th, td { border: 1px solid #bbb; padding: 6px 8px; text-align: left; vertical-align: top; }
  th { background: #f0f0f0; text-transform: uppercase; letter-spacing: 0.5px; }
  .footer { margin-top: 16px; font-size: 10px; color: #777; }
  @media print { body { padding: 8px; } }
</style></head><body>
<div class="header">
  <div><h1>ARROW DELIVERY</h1><div class="sub">${title || 'Bulk Order List'} — ${new Date().toLocaleString()}</div></div>
  <div class="sub">${rows.length} record(s)</div>
</div>
<table>
  <thead><tr>${head}</tr></thead>
  <tbody>${body}</tbody>
</table>
<div class="footer">Generated by Arrow Delivery platform.</div>
<script>window.onload = function(){ window.focus(); window.print(); };</script>
</body></html>`);
  w.document.close();
}