-- Migration: pricing & stations tables
-- Run this once in the Supabase SQL Editor.
-- Backs the admin Command Center "Network Coverage" and "Pickup Stations" cards
-- with real database rows instead of the bundled static constants. The app
-- auto-seeds these tables (admin session, empty tables only); public pages
-- keep read access via RLS.

CREATE TABLE IF NOT EXISTS public.pricing (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city text NOT NULL,
  zone integer NOT NULL DEFAULT 0,
  silver_domicile numeric NOT NULL DEFAULT 0,
  silver_stop numeric NOT NULL DEFAULT 0,
  gold_domicile numeric NOT NULL DEFAULT 0,
  gold_stop numeric NOT NULL DEFAULT 0,
  platinum_domicile numeric NOT NULL DEFAULT 0,
  platinum_stop numeric NOT NULL DEFAULT 0,
  domicile numeric,
  stop numeric
);

CREATE TABLE IF NOT EXISTS public.stations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wilaya text NOT NULL,
  name text NOT NULL,
  address text,
  phone text,
  maps_url text
);

-- SECURITY DEFINER so RLS policies can verify the caller's role safely
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = auth.uid() AND p.role = 'admin'
  );
$$;

ALTER TABLE public.pricing ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stations ENABLE ROW LEVEL SECURITY;

-- Public read: required by the public Home (+"/pricing") pages and dashboards
DROP POLICY IF EXISTS "pricing_public_read" ON public.pricing;
CREATE POLICY "pricing_public_read" ON public.pricing
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "stations_public_read" ON public.stations;
CREATE POLICY "stations_public_read" ON public.stations
  FOR SELECT USING (true);

-- Admin-only writes
DROP POLICY IF EXISTS "pricing_admin_write" ON public.pricing;
CREATE POLICY "pricing_admin_write" ON public.pricing
  FOR ALL
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "stations_admin_write" ON public.stations;
CREATE POLICY "stations_admin_write" ON public.stations
  FOR ALL
  USING (public.is_admin())
  WITH CHECK (public.is_admin());